---
title: "R Notebook"
output: html_notebook
---

```{r}
jamie_theme <- theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(colour = "grey60"),
        panel.grid = element_line(colour = "grey94"))
```





```{r}
bikes %>% 
  index_by(week) %>% 
  group_by(week, bike_id) %>% 
  summarise(rides = n()) %>% 
  index_by(week) %>% 
  summarise(n = sum(rides) / n()) %>% 
  mutate(n_rides_ma = slide_dbl(n, 
                             ~ mean(., na.rm = TRUE),
                             .before = 2,
                             .after = 2)) %>% 
  ggplot(aes(x = week)) +
  geom_line(aes(y = n, colour = "gray")) +
  geom_line(aes(y = n_rides_ma, colour = "red")) +
  labs(title = "Rides per Bike vs Week of the Year, 2018", 
       y= "Rides per Bike", x = "Date") +
  jamie_theme +
  scale_colour_manual(name = 'Data Type', 
                      values =c('gray'='gray','red'='red'), 
                      labels = c('Daily Value','Monthly Rolling\n Average')) +
  scale_x_continuous(breaks = seq(0, 53, 5))+
  scale_y_continuous(breaks = seq(0, 25, 5)) 



```




```{r}

bikes %>% 
  index_by(week) %>% 
  distinct(bike_id) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = week, y = n, colour = "red")) +
  geom_line(size = 1) +
  scale_colour_brewer(palette = "Set2") +
  jamie_theme +
  labs(title = "Number of Bikes Ridden per Week, 2018", 
       y = "Bikes", 
       x = "Week of the Year") +
  scale_x_continuous(breaks = seq(0, 53, 5))+ 
  scale_y_continuous(breaks = seq(0, 8, 1), limits = c(0, 9))+ 
  guides(colour = "none") 


```


```{r}
bikes %>%
  index_by(date) %>% 
  group_by(bike_id) %>% 
  summarise(n = n()) %>% 
  count(n) %>% 
  ggplot(aes(x = n, y = nn)) +
  geom_col()

bikes %>%
  index_by(month) %>% 
  group_by(bike_id) %>% 
  summarise(n = n()) %>% 
  count(n) %>% 
  ggplot(aes(x = n, y = nn)) +
  geom_col()
```

```{r}
bikes %>% 
  index_by(week) %>% 
  summarise(number_of_rides = n()) %>% 
  mutate(n_rides_ma = slide_dbl(number_of_rides, 
                                ~ mean(., na.rm = TRUE),
                                .before = 2,
                                .after = 2)) %>% 
  ggplot(aes(x = week)) +
  geom_line(aes(y = number_of_rides, colour = "gray")) +
  geom_line(aes(y = n_rides_ma, colour = "red")) +
  jamie_theme +
  labs(title = "Total Rides per Week vs Week of the Year, 2018", 
       y= "Rides", 
       x = "Week") +
  scale_colour_manual(name = 'Data Type', 
                      values =c('gray'='gray','red'='red'), 
                      labels = c('Daily Value','Monthly Rolling\n Average'))+
  scale_x_continuous(breaks = seq(0, 53, 5))+
  scale_y_continuous(breaks = seq(0, 175, 25))
```

```{r}
bikes %>% 
  index_by(time) %>% 
  filter(!weekday %in% c("Saturday", "Sunday"),
         time %in% as_hms(c("07:00:00", "08:00:00", "09:00:00", "17:00:00", "18:00:00", "19:00:00", "20:00:00")))

bikes

2070/4268
```

